baseURL = "https://cuonglm.xyz"
languageCode = "en-us"
title = "CuongLM"
theme = "minimal"

[params]
    author = "Cuong Manh Le"
    description = "go func(){}()"
    githubUsername = "cuonglm"
    accent = "#00BCEB"
    showBorder = true
    backgroundColor = "white"
    font = "Droid Sans Mono"
    highlight = true
    highlightStyle = "solarized-light"
    highlightLanguages = ["go", "sh", "bash", "json", "perl", "python", "rust"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.icon]]
    url = "CuongLM_Resume.pdf"
    name = "fas fa-file-alt"
    weight = 1

[[menu.icon]]
    url = "mailto:cuong.manhle.vn@gmail.com"
    name = "fas fa-envelope"
    weight = 2

[[menu.icon]]
    url = "https://github.com/cuonglm"
    name = "fab fa-github"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/cuonglm_"
    name = "fab fa-twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/bino18"
    name = "fab fa-linkedin"
    weight = 5

[[menu.icon]]
    url = "https://stackexchange.com/users/2556963/cuonglm"
    name = "fab fa-stack-exchange"
    weight = 6

[[menu.icon]]
    url = "https://go-review.googlesource.com/q/owner:cuong.manhle.vn%2540gmail.com"
    name = "fab fa-google"
    weight = 7
